# Generated by Django 4.1.7 on 2024-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0005_alter_message_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="censured_text",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
