# Generated by Django 4.1.7 on 2023-12-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
