# Generated by Django 4.2.8 on 2024-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amountOfMessages',
            field=models.IntegerField(default=1),
        ),
    ]
