# Generated by Django 4.2.8 on 2024-01-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_amountofmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terminalName',
            field=models.CharField(default='cybersan.com', max_length=30),
        ),
    ]
