# Generated by Django 4.2.8 on 2024-01-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
